// Comprehensive Service Menu Library
// 25 occupational categories with 50 services each (1,250 total services)

export interface LibraryService {
  name: string;
  price: number;
  duration?: number;
}

export interface ServiceCategory {
  id: string;
  name: string;
  description: string;
  icon: string;
  themeColor: string;
  altColor: string;
  businessType: 'mobile' | 'stationary';
  services: LibraryService[];
}

export const SERVICE_LIBRARY: ServiceCategory[] = [
  // 1. Handyman
  {
    id: 'handyman',
    name: 'Handyman',
    description: 'General repairs, installations, home maintenance',
    icon: 'Wrench',
    themeColor: '25 70% 45%',
    altColor: '20 25% 30%',
    businessType: 'mobile',
    services: [
      { name: 'Door Installation', price: 150, duration: 120 },
      { name: 'Door Repair', price: 85, duration: 60 },
      { name: 'Window Installation', price: 200, duration: 150 },
      { name: 'Window Repair', price: 95, duration: 60 },
      { name: 'Drywall Patching', price: 75, duration: 45 },
      { name: 'Drywall Installation', price: 250, duration: 240 },
      { name: 'Ceiling Fan Installation', price: 125, duration: 90 },
      { name: 'Light Fixture Installation', price: 85, duration: 45 },
      { name: 'Shelf Installation', price: 65, duration: 45 },
      { name: 'Cabinet Installation', price: 350, duration: 300 },
      { name: 'Cabinet Repair', price: 95, duration: 60 },
      { name: 'Furniture Assembly', price: 75, duration: 60 },
      { name: 'Picture Hanging', price: 45, duration: 30 },
      { name: 'Mirror Installation', price: 65, duration: 45 },
      { name: 'Curtain Rod Installation', price: 55, duration: 30 },
      { name: 'Blinds Installation', price: 75, duration: 45 },
      { name: 'Weather Stripping', price: 65, duration: 45 },
      { name: 'Caulking Services', price: 55, duration: 30 },
      { name: 'Tile Repair', price: 125, duration: 90 },
      { name: 'Grout Cleaning', price: 85, duration: 60 },
      { name: 'Grout Repair', price: 95, duration: 60 },
      { name: 'Baseboard Installation', price: 150, duration: 120 },
      { name: 'Crown Molding Installation', price: 200, duration: 180 },
      { name: 'Trim Installation', price: 125, duration: 90 },
      { name: 'Deck Repair', price: 175, duration: 150 },
      { name: 'Fence Repair', price: 150, duration: 120 },
      { name: 'Gate Installation', price: 200, duration: 180 },
      { name: 'Mailbox Installation', price: 75, duration: 45 },
      { name: 'House Number Installation', price: 35, duration: 20 },
      { name: 'Smoke Detector Installation', price: 45, duration: 30 },
      { name: 'CO Detector Installation', price: 45, duration: 30 },
      { name: 'Doorbell Installation', price: 65, duration: 45 },
      { name: 'Smart Doorbell Installation', price: 95, duration: 60 },
      { name: 'Lock Installation', price: 85, duration: 45 },
      { name: 'Lock Repair', price: 65, duration: 30 },
      { name: 'Deadbolt Installation', price: 95, duration: 60 },
      { name: 'Screen Door Repair', price: 75, duration: 45 },
      { name: 'Screen Replacement', price: 55, duration: 30 },
      { name: 'Storm Door Installation', price: 175, duration: 120 },
      { name: 'Pet Door Installation', price: 125, duration: 90 },
      { name: 'Attic Access Installation', price: 200, duration: 180 },
      { name: 'Handrail Installation', price: 150, duration: 120 },
      { name: 'Baby Gate Installation', price: 55, duration: 30 },
      { name: 'Towel Bar Installation', price: 45, duration: 30 },
      { name: 'TP Holder Installation', price: 35, duration: 20 },
      { name: 'Grab Bar Installation', price: 85, duration: 45 },
      { name: 'Closet Organizer Installation', price: 250, duration: 240 },
      { name: 'Garage Shelving', price: 175, duration: 150 },
      { name: 'Wall Anchor Installation', price: 45, duration: 30 },
      { name: 'General Repairs', price: 85, duration: 60 },
    ],
  },

  // 2. Plumbing
  {
    id: 'plumbing',
    name: 'Plumbing',
    description: 'Pipe repair, fixture installation, drain cleaning',
    icon: 'Droplets',
    themeColor: '200 60% 40%',
    altColor: '200 30% 30%',
    businessType: 'mobile',
    services: [
      { name: 'Leak Repair', price: 125, duration: 60 },
      { name: 'Faucet Installation', price: 150, duration: 90 },
      { name: 'Faucet Repair', price: 95, duration: 45 },
      { name: 'Toilet Installation', price: 200, duration: 120 },
      { name: 'Toilet Repair', price: 125, duration: 60 },
      { name: 'Drain Cleaning', price: 150, duration: 60 },
      { name: 'Clogged Drain Repair', price: 175, duration: 90 },
      { name: 'Water Heater Installation', price: 500, duration: 300 },
      { name: 'Water Heater Repair', price: 200, duration: 120 },
      { name: 'Tankless Water Heater Install', price: 750, duration: 360 },
      { name: 'Garbage Disposal Install', price: 175, duration: 90 },
      { name: 'Garbage Disposal Repair', price: 125, duration: 60 },
      { name: 'Dishwasher Installation', price: 175, duration: 90 },
      { name: 'Washing Machine Hookup', price: 125, duration: 60 },
      { name: 'Sink Installation', price: 250, duration: 150 },
      { name: 'Sink Repair', price: 125, duration: 60 },
      { name: 'Pipe Repair', price: 150, duration: 90 },
      { name: 'Pipe Replacement', price: 300, duration: 180 },
      { name: 'Sewer Line Cleaning', price: 250, duration: 120 },
      { name: 'Sewer Line Repair', price: 500, duration: 300 },
      { name: 'Water Line Repair', price: 350, duration: 180 },
      { name: 'Gas Line Installation', price: 400, duration: 240 },
      { name: 'Gas Line Repair', price: 250, duration: 120 },
      { name: 'Sump Pump Installation', price: 450, duration: 240 },
      { name: 'Sump Pump Repair', price: 200, duration: 120 },
      { name: 'Water Softener Installation', price: 350, duration: 180 },
      { name: 'Water Filtration Install', price: 300, duration: 150 },
      { name: 'Pressure Regulator Install', price: 200, duration: 90 },
      { name: 'Shut-Off Valve Install', price: 150, duration: 60 },
      { name: 'Hose Bib Repair', price: 95, duration: 45 },
      { name: 'Outdoor Faucet Install', price: 175, duration: 90 },
      { name: 'Bathtub Installation', price: 600, duration: 360 },
      { name: 'Shower Installation', price: 500, duration: 300 },
      { name: 'Shower Head Replacement', price: 75, duration: 30 },
      { name: 'Shower Valve Repair', price: 200, duration: 120 },
      { name: 'Bathtub Drain Repair', price: 150, duration: 90 },
      { name: 'Toilet Flange Repair', price: 175, duration: 90 },
      { name: 'Wax Ring Replacement', price: 125, duration: 60 },
      { name: 'P-Trap Replacement', price: 95, duration: 45 },
      { name: 'Water Pressure Testing', price: 75, duration: 30 },
      { name: 'Backflow Prevention', price: 250, duration: 120 },
      { name: 'Hydro Jetting', price: 350, duration: 120 },
      { name: 'Camera Inspection', price: 200, duration: 60 },
      { name: 'Septic Tank Pumping', price: 400, duration: 120 },
      { name: 'Well Pump Repair', price: 350, duration: 180 },
      { name: 'Expansion Tank Install', price: 175, duration: 90 },
      { name: 'Recirculating Pump Install', price: 300, duration: 150 },
      { name: 'Emergency Plumbing', price: 200, duration: 60 },
      { name: 'Winterization Services', price: 150, duration: 90 },
      { name: 'Plumbing Inspection', price: 95, duration: 60 },
    ],
  },

  // 3. Salon
  {
    id: 'salon',
    name: 'Salon',
    description: 'Full-service hair salon and beauty treatments',
    icon: 'Sparkles',
    themeColor: '330 50% 45%',
    altColor: '330 30% 30%',
    businessType: 'stationary',
    services: [
      { name: 'Haircut - Women', price: 45, duration: 45 },
      { name: 'Haircut - Men', price: 30, duration: 30 },
      { name: 'Haircut - Children', price: 25, duration: 25 },
      { name: 'Hair Coloring', price: 85, duration: 90 },
      { name: 'Highlights', price: 120, duration: 120 },
      { name: 'Lowlights', price: 100, duration: 90 },
      { name: 'Balayage', price: 175, duration: 150 },
      { name: 'Ombre', price: 150, duration: 120 },
      { name: 'Root Touch-Up', price: 65, duration: 45 },
      { name: 'Gray Coverage', price: 75, duration: 60 },
      { name: 'Hair Gloss', price: 45, duration: 30 },
      { name: 'Hair Toner', price: 35, duration: 20 },
      { name: 'Deep Conditioning', price: 35, duration: 30 },
      { name: 'Keratin Treatment', price: 250, duration: 180 },
      { name: 'Brazilian Blowout', price: 300, duration: 210 },
      { name: 'Hair Straightening', price: 200, duration: 150 },
      { name: 'Perm', price: 150, duration: 150 },
      { name: 'Tape-In Extensions', price: 350, duration: 180 },
      { name: 'Sew-In Extensions', price: 400, duration: 240 },
      { name: 'Clip-In Extensions', price: 150, duration: 60 },
      { name: 'Fusion Extensions', price: 500, duration: 300 },
      { name: 'Updo Styling', price: 75, duration: 60 },
      { name: 'Bridal Hair', price: 150, duration: 90 },
      { name: 'Special Occasion Styling', price: 85, duration: 60 },
      { name: 'Blowout', price: 45, duration: 45 },
      { name: 'Wash and Style', price: 35, duration: 30 },
      { name: 'Scalp Treatment', price: 45, duration: 30 },
      { name: 'Hair Mask', price: 35, duration: 30 },
      { name: 'Split End Treatment', price: 25, duration: 20 },
      { name: 'Bang Trim', price: 15, duration: 10 },
      { name: 'Beard Trim', price: 20, duration: 15 },
      { name: 'Eyebrow Shaping', price: 20, duration: 15 },
      { name: 'Eyebrow Tinting', price: 25, duration: 20 },
      { name: 'Eyelash Tinting', price: 30, duration: 25 },
      { name: 'Facial Waxing', price: 35, duration: 20 },
      { name: 'Lip Waxing', price: 15, duration: 10 },
      { name: 'Chin Waxing', price: 15, duration: 10 },
      { name: 'Full Face Waxing', price: 55, duration: 30 },
      { name: 'Leg Waxing', price: 65, duration: 45 },
      { name: 'Arm Waxing', price: 45, duration: 30 },
      { name: 'Bikini Waxing', price: 45, duration: 30 },
      { name: 'Brazilian Waxing', price: 75, duration: 45 },
      { name: 'Manicure', price: 25, duration: 30 },
      { name: 'Pedicure', price: 40, duration: 45 },
      { name: 'Gel Manicure', price: 40, duration: 45 },
      { name: 'Gel Pedicure', price: 55, duration: 60 },
      { name: 'Nail Art', price: 15, duration: 20 },
      { name: 'Acrylic Nails', price: 65, duration: 75 },
      { name: 'Nail Repair', price: 10, duration: 10 },
      { name: 'Polish Change', price: 15, duration: 15 },
    ],
  },

  // 4. Barber
  {
    id: 'barber',
    name: 'Barber',
    description: 'Men\'s haircuts, fades, beard grooming',
    icon: 'Scissors',
    themeColor: '215 50% 23%',
    altColor: '215 19% 35%',
    businessType: 'stationary',
    services: [
      { name: 'Men\'s Haircut', price: 25, duration: 30 },
      { name: 'Boy\'s Haircut', price: 20, duration: 25 },
      { name: 'Senior Haircut', price: 20, duration: 25 },
      { name: 'Buzz Cut', price: 20, duration: 20 },
      { name: 'Fade Haircut', price: 30, duration: 35 },
      { name: 'Taper Fade', price: 28, duration: 30 },
      { name: 'Skin Fade', price: 30, duration: 35 },
      { name: 'Low Fade', price: 28, duration: 30 },
      { name: 'Mid Fade', price: 28, duration: 30 },
      { name: 'High Fade', price: 30, duration: 35 },
      { name: 'Temple Fade', price: 28, duration: 30 },
      { name: 'Drop Fade', price: 30, duration: 35 },
      { name: 'Undercut', price: 30, duration: 30 },
      { name: 'Crew Cut', price: 25, duration: 25 },
      { name: 'Flat Top', price: 30, duration: 35 },
      { name: 'Mohawk', price: 35, duration: 40 },
      { name: 'Faux Hawk', price: 30, duration: 35 },
      { name: 'Caesar Cut', price: 25, duration: 25 },
      { name: 'Ivy League Cut', price: 28, duration: 30 },
      { name: 'Pompadour', price: 35, duration: 40 },
      { name: 'Quiff', price: 30, duration: 35 },
      { name: 'Slick Back', price: 28, duration: 30 },
      { name: 'Comb Over', price: 28, duration: 30 },
      { name: 'Side Part', price: 25, duration: 25 },
      { name: 'Textured Crop', price: 28, duration: 30 },
      { name: 'Line Up', price: 12, duration: 10 },
      { name: 'Edge Up', price: 10, duration: 10 },
      { name: 'Shape Up', price: 15, duration: 15 },
      { name: 'Beard Trim', price: 15, duration: 15 },
      { name: 'Beard Shaping', price: 20, duration: 20 },
      { name: 'Beard Lineup', price: 12, duration: 10 },
      { name: 'Full Beard Grooming', price: 25, duration: 25 },
      { name: 'Goatee Trim', price: 15, duration: 15 },
      { name: 'Mustache Trim', price: 10, duration: 10 },
      { name: 'Sideburn Trim', price: 8, duration: 5 },
      { name: 'Neck Trim', price: 10, duration: 10 },
      { name: 'Eyebrow Trim', price: 10, duration: 10 },
      { name: 'Ear Hair Trim', price: 5, duration: 5 },
      { name: 'Nose Hair Trim', price: 5, duration: 5 },
      { name: 'Hot Towel Shave', price: 30, duration: 30 },
      { name: 'Straight Razor Shave', price: 35, duration: 35 },
      { name: 'Head Shave', price: 30, duration: 30 },
      { name: 'Bald Fade', price: 32, duration: 35 },
      { name: 'Hair Design', price: 25, duration: 30 },
      { name: 'Hair Tattoo', price: 30, duration: 30 },
      { name: 'Gray Blending', price: 35, duration: 30 },
      { name: 'Hair Coloring - Men', price: 50, duration: 60 },
      { name: 'Scalp Treatment', price: 25, duration: 20 },
      { name: 'Hair Wash', price: 10, duration: 10 },
      { name: 'Conditioning Treatment', price: 20, duration: 25 },
    ],
  },

  // 5. Cleaning
  {
    id: 'cleaning',
    name: 'Cleaning',
    description: 'Residential and commercial cleaning services',
    icon: 'Sparkles',
    themeColor: '180 50% 40%',
    altColor: '180 30% 25%',
    businessType: 'mobile',
    services: [
      { name: 'Standard House Cleaning', price: 150, duration: 180 },
      { name: 'Deep Cleaning', price: 250, duration: 300 },
      { name: 'Move-In Cleaning', price: 300, duration: 360 },
      { name: 'Move-Out Cleaning', price: 300, duration: 360 },
      { name: 'Post-Construction Cleaning', price: 400, duration: 480 },
      { name: 'Office Cleaning', price: 175, duration: 180 },
      { name: 'Commercial Cleaning', price: 250, duration: 240 },
      { name: 'Apartment Cleaning', price: 125, duration: 150 },
      { name: 'Condo Cleaning', price: 150, duration: 180 },
      { name: 'Kitchen Deep Clean', price: 85, duration: 90 },
      { name: 'Bathroom Deep Clean', price: 65, duration: 60 },
      { name: 'Bedroom Cleaning', price: 45, duration: 45 },
      { name: 'Living Room Cleaning', price: 55, duration: 60 },
      { name: 'Carpet Cleaning', price: 125, duration: 120 },
      { name: 'Upholstery Cleaning', price: 95, duration: 90 },
      { name: 'Window Cleaning - Interior', price: 75, duration: 60 },
      { name: 'Window Cleaning - Exterior', price: 125, duration: 120 },
      { name: 'Blind Cleaning', price: 45, duration: 45 },
      { name: 'Ceiling Fan Cleaning', price: 25, duration: 20 },
      { name: 'Baseboard Cleaning', price: 35, duration: 30 },
      { name: 'Wall Washing', price: 95, duration: 90 },
      { name: 'Cabinet Cleaning', price: 55, duration: 45 },
      { name: 'Appliance Cleaning', price: 45, duration: 45 },
      { name: 'Oven Cleaning', price: 55, duration: 60 },
      { name: 'Refrigerator Cleaning', price: 45, duration: 45 },
      { name: 'Microwave Cleaning', price: 15, duration: 15 },
      { name: 'Dishwasher Cleaning', price: 25, duration: 20 },
      { name: 'Laundry Service', price: 45, duration: 60 },
      { name: 'Ironing Service', price: 35, duration: 45 },
      { name: 'Bed Making', price: 15, duration: 15 },
      { name: 'Linen Change', price: 25, duration: 20 },
      { name: 'Trash Removal', price: 25, duration: 20 },
      { name: 'Recycling', price: 15, duration: 15 },
      { name: 'Floor Mopping', price: 35, duration: 30 },
      { name: 'Floor Vacuuming', price: 25, duration: 25 },
      { name: 'Floor Waxing', price: 85, duration: 90 },
      { name: 'Tile and Grout Cleaning', price: 95, duration: 90 },
      { name: 'Hardwood Floor Cleaning', price: 75, duration: 60 },
      { name: 'Dusting', price: 35, duration: 30 },
      { name: 'Cobweb Removal', price: 25, duration: 20 },
      { name: 'Light Fixture Cleaning', price: 35, duration: 30 },
      { name: 'Mirror Cleaning', price: 15, duration: 15 },
      { name: 'Glass Cleaning', price: 25, duration: 20 },
      { name: 'Sanitization Service', price: 95, duration: 60 },
      { name: 'Disinfection Service', price: 125, duration: 90 },
      { name: 'Hoarding Cleanup', price: 500, duration: 480 },
      { name: 'Estate Cleanout', price: 400, duration: 360 },
      { name: 'Garage Cleaning', price: 125, duration: 120 },
      { name: 'Patio Cleaning', price: 75, duration: 60 },
      { name: 'Pressure Washing', price: 150, duration: 120 },
    ],
  },

  // 6. Pet Grooming
  {
    id: 'pet_grooming',
    name: 'Pet Grooming',
    description: 'Dog and cat grooming, bathing, styling',
    icon: 'Dog',
    themeColor: '35 60% 50%',
    altColor: '35 40% 35%',
    businessType: 'stationary',
    services: [
      { name: 'Full Groom - Small Dog', price: 55, duration: 90 },
      { name: 'Full Groom - Medium Dog', price: 70, duration: 120 },
      { name: 'Full Groom - Large Dog', price: 95, duration: 150 },
      { name: 'Full Groom - Cat', price: 75, duration: 120 },
      { name: 'Bath & Brush - Small Dog', price: 35, duration: 45 },
      { name: 'Bath & Brush - Medium Dog', price: 45, duration: 60 },
      { name: 'Bath & Brush - Large Dog', price: 60, duration: 75 },
      { name: 'Puppy\'s First Groom', price: 45, duration: 60 },
      { name: 'Senior Pet Groom', price: 65, duration: 90 },
      { name: 'De-Shedding Treatment', price: 35, duration: 45 },
      { name: 'Breed Specific Haircut', price: 65, duration: 90 },
      { name: 'Custom Style Haircut', price: 75, duration: 120 },
      { name: 'Face Trim', price: 15, duration: 15 },
      { name: 'Ear Cleaning', price: 15, duration: 15 },
      { name: 'Ear Hair Removal', price: 10, duration: 10 },
      { name: 'Nail Trim', price: 15, duration: 15 },
      { name: 'Nail Grinding', price: 20, duration: 20 },
      { name: 'Paw Pad Trim', price: 10, duration: 10 },
      { name: 'Sanitary Trim', price: 15, duration: 15 },
      { name: 'Tail Trim', price: 10, duration: 10 },
      { name: 'Teeth Brushing', price: 15, duration: 15 },
      { name: 'Breath Freshening', price: 10, duration: 10 },
      { name: 'Flea Bath', price: 25, duration: 45 },
      { name: 'Medicated Bath', price: 35, duration: 60 },
      { name: 'Hypoallergenic Bath', price: 30, duration: 45 },
      { name: 'Oatmeal Bath', price: 25, duration: 45 },
      { name: 'Whitening Bath', price: 30, duration: 60 },
      { name: 'De-Matting', price: 25, duration: 30 },
      { name: 'Coat Conditioning', price: 20, duration: 20 },
      { name: 'Hot Oil Treatment', price: 25, duration: 30 },
      { name: 'Blueberry Facial', price: 15, duration: 15 },
      { name: 'Anal Gland Expression', price: 15, duration: 10 },
      { name: 'Skunk Odor Removal', price: 50, duration: 90 },
      { name: 'Coat Coloring', price: 45, duration: 60 },
      { name: 'Creative Grooming', price: 75, duration: 120 },
      { name: 'Feather Extensions', price: 20, duration: 20 },
      { name: 'Nail Polish', price: 15, duration: 15 },
      { name: 'Bandana Application', price: 5, duration: 5 },
      { name: 'Bow Application', price: 5, duration: 5 },
      { name: 'Cologne Application', price: 5, duration: 5 },
      { name: 'Hand Stripping', price: 85, duration: 120 },
      { name: 'Carding', price: 35, duration: 45 },
      { name: 'Scissor Finish', price: 20, duration: 30 },
      { name: 'Clipper Cut', price: 45, duration: 60 },
      { name: 'Mobile Grooming', price: 95, duration: 120 },
      { name: 'Express Groom', price: 40, duration: 30 },
      { name: 'Spa Package', price: 95, duration: 120 },
      { name: 'Luxury Groom', price: 125, duration: 150 },
      { name: 'Puppy Package', price: 55, duration: 75 },
      { name: 'Maintenance Groom', price: 45, duration: 45 },
    ],
  },

  // 7. Lawn Care
  {
    id: 'lawn_care',
    name: 'Lawn Care',
    description: 'Mowing, trimming, fertilization, yard maintenance',
    icon: 'Trees',
    themeColor: '120 40% 35%',
    altColor: '120 30% 25%',
    businessType: 'mobile',
    services: [
      { name: 'Lawn Mowing', price: 45, duration: 45 },
      { name: 'Edging', price: 25, duration: 20 },
      { name: 'Trimming', price: 25, duration: 20 },
      { name: 'Leaf Removal', price: 75, duration: 60 },
      { name: 'Leaf Blowing', price: 45, duration: 30 },
      { name: 'Grass Clipping Removal', price: 25, duration: 15 },
      { name: 'Lawn Fertilization', price: 75, duration: 45 },
      { name: 'Weed Control', price: 65, duration: 45 },
      { name: 'Pre-Emergent Application', price: 85, duration: 45 },
      { name: 'Post-Emergent Application', price: 75, duration: 45 },
      { name: 'Lawn Aeration', price: 125, duration: 90 },
      { name: 'Overseeding', price: 95, duration: 60 },
      { name: 'Dethatching', price: 150, duration: 120 },
      { name: 'Lawn Rolling', price: 85, duration: 60 },
      { name: 'Soil Testing', price: 45, duration: 30 },
      { name: 'pH Balancing', price: 75, duration: 45 },
      { name: 'Grub Control', price: 95, duration: 45 },
      { name: 'Insect Treatment', price: 85, duration: 45 },
      { name: 'Fungicide Application', price: 95, duration: 45 },
      { name: 'Disease Treatment', price: 125, duration: 60 },
      { name: 'Lawn Repair', price: 150, duration: 120 },
      { name: 'Sod Installation', price: 350, duration: 240 },
      { name: 'Seed Installation', price: 175, duration: 120 },
      { name: 'Hydroseeding', price: 400, duration: 180 },
      { name: 'Lawn Leveling', price: 200, duration: 150 },
      { name: 'Top Dressing', price: 150, duration: 90 },
      { name: 'Mulching', price: 125, duration: 90 },
      { name: 'Bed Edging', price: 75, duration: 60 },
      { name: 'Shrub Trimming', price: 65, duration: 45 },
      { name: 'Hedge Trimming', price: 85, duration: 60 },
      { name: 'Bush Shaping', price: 55, duration: 45 },
      { name: 'Tree Trimming', price: 150, duration: 120 },
      { name: 'Branch Removal', price: 125, duration: 90 },
      { name: 'Stump Grinding', price: 200, duration: 120 },
      { name: 'Yard Cleanup', price: 125, duration: 120 },
      { name: 'Spring Cleanup', price: 175, duration: 180 },
      { name: 'Fall Cleanup', price: 200, duration: 180 },
      { name: 'Gutter Cleaning', price: 95, duration: 60 },
      { name: 'Downspout Cleaning', price: 45, duration: 30 },
      { name: 'Irrigation Inspection', price: 65, duration: 45 },
      { name: 'Sprinkler Repair', price: 95, duration: 60 },
      { name: 'Sprinkler Adjustment', price: 55, duration: 30 },
      { name: 'Winterization', price: 85, duration: 60 },
      { name: 'Spring Activation', price: 75, duration: 45 },
      { name: 'Snow Removal', price: 75, duration: 60 },
      { name: 'Ice Management', price: 65, duration: 45 },
      { name: 'Salt Application', price: 45, duration: 30 },
      { name: 'Debris Removal', price: 85, duration: 60 },
      { name: 'Storm Cleanup', price: 175, duration: 180 },
      { name: 'Seasonal Maintenance', price: 125, duration: 90 },
    ],
  },

  // 8. Electrical
  {
    id: 'electrical',
    name: 'Electrical',
    description: 'Wiring, outlets, panel upgrades, lighting',
    icon: 'Zap',
    themeColor: '45 80% 50%',
    altColor: '45 60% 35%',
    businessType: 'mobile',
    services: [
      { name: 'Outlet Installation', price: 95, duration: 45 },
      { name: 'Outlet Repair', price: 75, duration: 30 },
      { name: 'GFCI Outlet Installation', price: 125, duration: 60 },
      { name: 'USB Outlet Installation', price: 115, duration: 45 },
      { name: 'Switch Installation', price: 85, duration: 30 },
      { name: 'Dimmer Switch Installation', price: 125, duration: 45 },
      { name: 'Smart Switch Installation', price: 150, duration: 60 },
      { name: 'Three-Way Switch Install', price: 175, duration: 90 },
      { name: 'Light Fixture Installation', price: 125, duration: 60 },
      { name: 'Ceiling Fan Installation', price: 175, duration: 90 },
      { name: 'Chandelier Installation', price: 225, duration: 120 },
      { name: 'Recessed Lighting Install', price: 150, duration: 90 },
      { name: 'Under Cabinet Lighting', price: 200, duration: 120 },
      { name: 'LED Conversion', price: 125, duration: 60 },
      { name: 'Track Lighting Install', price: 175, duration: 90 },
      { name: 'Outdoor Lighting', price: 200, duration: 120 },
      { name: 'Security Lighting', price: 175, duration: 90 },
      { name: 'Motion Sensor Install', price: 125, duration: 60 },
      { name: 'Landscape Lighting', price: 300, duration: 180 },
      { name: 'Panel Upgrade', price: 1500, duration: 480 },
      { name: 'Circuit Breaker Replace', price: 175, duration: 60 },
      { name: 'Fuse Box Upgrade', price: 1200, duration: 360 },
      { name: 'Whole House Surge Protect', price: 350, duration: 120 },
      { name: 'Dedicated Circuit Install', price: 275, duration: 120 },
      { name: '240V Outlet Installation', price: 350, duration: 180 },
      { name: 'EV Charger Installation', price: 600, duration: 240 },
      { name: 'Generator Installation', price: 1000, duration: 360 },
      { name: 'Transfer Switch Install', price: 500, duration: 180 },
      { name: 'Smoke Detector Install', price: 75, duration: 30 },
      { name: 'CO Detector Install', price: 75, duration: 30 },
      { name: 'Doorbell Installation', price: 95, duration: 45 },
      { name: 'Smart Doorbell Install', price: 150, duration: 60 },
      { name: 'Thermostat Installation', price: 125, duration: 60 },
      { name: 'Smart Thermostat Setup', price: 175, duration: 90 },
      { name: 'Ceiling Fan Wiring', price: 200, duration: 120 },
      { name: 'Exhaust Fan Installation', price: 175, duration: 90 },
      { name: 'Bathroom Fan Installation', price: 200, duration: 120 },
      { name: 'Attic Fan Installation', price: 300, duration: 180 },
      { name: 'Whole House Fan Install', price: 500, duration: 300 },
      { name: 'Hot Tub Wiring', price: 450, duration: 180 },
      { name: 'Pool Equipment Wiring', price: 400, duration: 180 },
      { name: 'Electrical Inspection', price: 125, duration: 60 },
      { name: 'Code Compliance', price: 200, duration: 120 },
      { name: 'Troubleshooting', price: 125, duration: 60 },
      { name: 'Wire Repair', price: 150, duration: 90 },
      { name: 'Junction Box Install', price: 95, duration: 45 },
      { name: 'Conduit Installation', price: 175, duration: 120 },
      { name: 'Emergency Service', price: 200, duration: 60 },
      { name: 'Electrical Safety Audit', price: 150, duration: 90 },
      { name: 'Home Rewiring', price: 3500, duration: 1440 },
    ],
  },

  // 9. HVAC
  {
    id: 'hvac',
    name: 'HVAC',
    description: 'Heating, ventilation, air conditioning services',
    icon: 'Wind',
    themeColor: '200 50% 45%',
    altColor: '200 35% 30%',
    businessType: 'mobile',
    services: [
      { name: 'AC Installation', price: 3500, duration: 480 },
      { name: 'AC Repair', price: 350, duration: 120 },
      { name: 'AC Maintenance', price: 150, duration: 90 },
      { name: 'Furnace Installation', price: 3000, duration: 480 },
      { name: 'Furnace Repair', price: 300, duration: 120 },
      { name: 'Furnace Maintenance', price: 150, duration: 90 },
      { name: 'Heat Pump Installation', price: 4000, duration: 540 },
      { name: 'Heat Pump Repair', price: 350, duration: 120 },
      { name: 'Ductless Mini-Split Install', price: 3500, duration: 480 },
      { name: 'Mini-Split Repair', price: 275, duration: 90 },
      { name: 'Thermostat Installation', price: 175, duration: 60 },
      { name: 'Smart Thermostat Setup', price: 225, duration: 90 },
      { name: 'Air Duct Cleaning', price: 400, duration: 240 },
      { name: 'Duct Sealing', price: 350, duration: 180 },
      { name: 'Duct Insulation', price: 500, duration: 300 },
      { name: 'Duct Repair', price: 250, duration: 120 },
      { name: 'Vent Cleaning', price: 150, duration: 90 },
      { name: 'Register Replacement', price: 75, duration: 30 },
      { name: 'Air Filter Replacement', price: 35, duration: 15 },
      { name: 'UV Light Installation', price: 400, duration: 120 },
      { name: 'Air Purifier Installation', price: 500, duration: 180 },
      { name: 'Humidifier Installation', price: 450, duration: 180 },
      { name: 'Dehumidifier Installation', price: 400, duration: 150 },
      { name: 'Zoning System Install', price: 2500, duration: 480 },
      { name: 'Zone Damper Repair', price: 200, duration: 90 },
      { name: 'Refrigerant Recharge', price: 250, duration: 60 },
      { name: 'Coil Cleaning', price: 175, duration: 90 },
      { name: 'Blower Motor Repair', price: 400, duration: 120 },
      { name: 'Compressor Repair', price: 600, duration: 180 },
      { name: 'Condenser Cleaning', price: 150, duration: 60 },
      { name: 'Evaporator Cleaning', price: 200, duration: 90 },
      { name: 'Capacitor Replacement', price: 200, duration: 45 },
      { name: 'Contactor Replacement', price: 175, duration: 45 },
      { name: 'Fan Motor Replacement', price: 350, duration: 90 },
      { name: 'Ignitor Replacement', price: 200, duration: 60 },
      { name: 'Heat Exchanger Inspection', price: 150, duration: 60 },
      { name: 'Carbon Monoxide Testing', price: 95, duration: 30 },
      { name: 'Combustion Analysis', price: 125, duration: 45 },
      { name: 'System Balancing', price: 250, duration: 120 },
      { name: 'Airflow Testing', price: 125, duration: 60 },
      { name: 'Energy Audit', price: 200, duration: 120 },
      { name: 'Efficiency Optimization', price: 175, duration: 90 },
      { name: 'Preventive Maintenance', price: 175, duration: 90 },
      { name: 'Seasonal Tune-Up', price: 150, duration: 90 },
      { name: 'Emergency Repair', price: 250, duration: 60 },
      { name: '24-Hour Service', price: 300, duration: 60 },
      { name: 'Commercial HVAC', price: 500, duration: 240 },
      { name: 'Rooftop Unit Service', price: 350, duration: 180 },
      { name: 'Package Unit Service', price: 300, duration: 150 },
      { name: 'Boiler Service', price: 275, duration: 120 },
    ],
  },

  // 10. Painting
  {
    id: 'painting',
    name: 'Painting',
    description: 'Interior and exterior painting, staining, finishing',
    icon: 'Paintbrush',
    themeColor: '270 40% 45%',
    altColor: '270 30% 30%',
    businessType: 'mobile',
    services: [
      { name: 'Interior Painting - Room', price: 350, duration: 480 },
      { name: 'Interior Painting - House', price: 2500, duration: 2400 },
      { name: 'Exterior Painting - House', price: 3500, duration: 2880 },
      { name: 'Exterior Painting - Trim', price: 800, duration: 480 },
      { name: 'Accent Wall Painting', price: 200, duration: 180 },
      { name: 'Ceiling Painting', price: 250, duration: 240 },
      { name: 'Cabinet Painting', price: 1200, duration: 960 },
      { name: 'Cabinet Refinishing', price: 1500, duration: 1200 },
      { name: 'Door Painting', price: 75, duration: 60 },
      { name: 'Window Frame Painting', price: 50, duration: 45 },
      { name: 'Baseboard Painting', price: 125, duration: 120 },
      { name: 'Crown Molding Painting', price: 150, duration: 120 },
      { name: 'Deck Staining', price: 500, duration: 480 },
      { name: 'Deck Sealing', price: 350, duration: 300 },
      { name: 'Fence Painting', price: 400, duration: 360 },
      { name: 'Fence Staining', price: 450, duration: 360 },
      { name: 'Garage Floor Painting', price: 400, duration: 360 },
      { name: 'Epoxy Floor Coating', price: 800, duration: 480 },
      { name: 'Concrete Staining', price: 350, duration: 300 },
      { name: 'Brick Painting', price: 600, duration: 480 },
      { name: 'Stucco Painting', price: 700, duration: 540 },
      { name: 'Popcorn Ceiling Removal', price: 500, duration: 480 },
      { name: 'Textured Ceiling Apply', price: 400, duration: 360 },
      { name: 'Wallpaper Removal', price: 300, duration: 360 },
      { name: 'Wallpaper Installation', price: 400, duration: 480 },
      { name: 'Faux Finish', price: 350, duration: 300 },
      { name: 'Decorative Painting', price: 450, duration: 360 },
      { name: 'Mural Painting', price: 800, duration: 960 },
      { name: 'Accent Painting', price: 175, duration: 120 },
      { name: 'Color Consultation', price: 75, duration: 60 },
      { name: 'Paint Matching', price: 50, duration: 30 },
      { name: 'Touch-Up Painting', price: 125, duration: 90 },
      { name: 'Drywall Repair', price: 150, duration: 120 },
      { name: 'Hole Patching', price: 75, duration: 45 },
      { name: 'Crack Repair', price: 100, duration: 60 },
      { name: 'Caulking', price: 75, duration: 60 },
      { name: 'Wood Repair', price: 150, duration: 120 },
      { name: 'Sanding', price: 125, duration: 90 },
      { name: 'Priming', price: 150, duration: 120 },
      { name: 'Pressure Washing', price: 200, duration: 120 },
      { name: 'Power Washing', price: 225, duration: 150 },
      { name: 'Surface Preparation', price: 175, duration: 180 },
      { name: 'Lead Paint Testing', price: 100, duration: 60 },
      { name: 'Lead Paint Abatement', price: 1500, duration: 960 },
      { name: 'Elastomeric Coating', price: 600, duration: 480 },
      { name: 'Waterproofing', price: 400, duration: 300 },
      { name: 'Anti-Graffiti Coating', price: 300, duration: 240 },
      { name: 'Commercial Painting', price: 2000, duration: 1440 },
      { name: 'Industrial Painting', price: 3000, duration: 1920 },
      { name: 'Specialty Coatings', price: 500, duration: 360 },
    ],
  },

  // 11. Tutoring
  {
    id: 'tutoring',
    name: 'Tutoring',
    description: 'Academic tutoring, test prep, learning support',
    icon: 'BookOpen',
    themeColor: '160 45% 40%',
    altColor: '160 30% 25%',
    businessType: 'stationary',
    services: [
      { name: 'Math - Elementary', price: 45, duration: 60 },
      { name: 'Math - Middle School', price: 50, duration: 60 },
      { name: 'Math - High School', price: 60, duration: 60 },
      { name: 'Algebra Tutoring', price: 55, duration: 60 },
      { name: 'Geometry Tutoring', price: 55, duration: 60 },
      { name: 'Calculus Tutoring', price: 70, duration: 60 },
      { name: 'Statistics Tutoring', price: 65, duration: 60 },
      { name: 'Reading Tutoring', price: 45, duration: 60 },
      { name: 'Writing Tutoring', price: 50, duration: 60 },
      { name: 'English Tutoring', price: 50, duration: 60 },
      { name: 'Literature Analysis', price: 55, duration: 60 },
      { name: 'Essay Writing Help', price: 60, duration: 60 },
      { name: 'Grammar Tutoring', price: 45, duration: 60 },
      { name: 'Vocabulary Building', price: 40, duration: 60 },
      { name: 'Science - General', price: 50, duration: 60 },
      { name: 'Biology Tutoring', price: 55, duration: 60 },
      { name: 'Chemistry Tutoring', price: 65, duration: 60 },
      { name: 'Physics Tutoring', price: 70, duration: 60 },
      { name: 'History Tutoring', price: 50, duration: 60 },
      { name: 'Geography Tutoring', price: 45, duration: 60 },
      { name: 'Social Studies', price: 50, duration: 60 },
      { name: 'Spanish Tutoring', price: 55, duration: 60 },
      { name: 'French Tutoring', price: 55, duration: 60 },
      { name: 'German Tutoring', price: 60, duration: 60 },
      { name: 'Mandarin Tutoring', price: 70, duration: 60 },
      { name: 'ESL Tutoring', price: 55, duration: 60 },
      { name: 'SAT Prep', price: 75, duration: 90 },
      { name: 'ACT Prep', price: 75, duration: 90 },
      { name: 'GRE Prep', price: 85, duration: 90 },
      { name: 'GMAT Prep', price: 90, duration: 90 },
      { name: 'LSAT Prep', price: 100, duration: 90 },
      { name: 'MCAT Prep', price: 100, duration: 90 },
      { name: 'AP Exam Prep', price: 70, duration: 60 },
      { name: 'Study Skills Coaching', price: 50, duration: 60 },
      { name: 'Homework Help', price: 40, duration: 60 },
      { name: 'Test Taking Strategies', price: 55, duration: 60 },
      { name: 'Time Management Coaching', price: 50, duration: 60 },
      { name: 'Organization Skills', price: 45, duration: 60 },
      { name: 'College Application Help', price: 75, duration: 90 },
      { name: 'Essay Editing', price: 60, duration: 60 },
      { name: 'Research Paper Help', price: 65, duration: 60 },
      { name: 'Presentation Skills', price: 55, duration: 60 },
      { name: 'Public Speaking', price: 60, duration: 60 },
      { name: 'Computer Skills', price: 50, duration: 60 },
      { name: 'Coding Tutoring', price: 70, duration: 60 },
      { name: 'Music Theory', price: 55, duration: 60 },
      { name: 'Art Instruction', price: 50, duration: 60 },
      { name: 'Special Education Support', price: 65, duration: 60 },
      { name: 'Learning Disability Support', price: 70, duration: 60 },
      { name: 'One-on-One Sessions', price: 55, duration: 60 },
    ],
  },

  // 12. Photography
  {
    id: 'photography',
    name: 'Photography',
    description: 'Portrait, event, commercial photography services',
    icon: 'Camera',
    themeColor: '0 0% 30%',
    altColor: '0 0% 20%',
    businessType: 'mobile',
    services: [
      { name: 'Portrait Photography', price: 150, duration: 60 },
      { name: 'Headshot Photography', price: 125, duration: 45 },
      { name: 'Family Portrait', price: 200, duration: 90 },
      { name: 'Couple Photography', price: 175, duration: 60 },
      { name: 'Engagement Photos', price: 300, duration: 120 },
      { name: 'Wedding Photography', price: 2500, duration: 480 },
      { name: 'Wedding Videography', price: 2000, duration: 480 },
      { name: 'Event Photography', price: 350, duration: 180 },
      { name: 'Birthday Party Photos', price: 250, duration: 120 },
      { name: 'Corporate Event Photos', price: 500, duration: 240 },
      { name: 'Product Photography', price: 200, duration: 120 },
      { name: 'Food Photography', price: 250, duration: 150 },
      { name: 'Real Estate Photography', price: 175, duration: 90 },
      { name: 'Architectural Photography', price: 300, duration: 180 },
      { name: 'Interior Photography', price: 200, duration: 120 },
      { name: 'Drone Photography', price: 350, duration: 120 },
      { name: 'Aerial Photography', price: 400, duration: 150 },
      { name: 'Landscape Photography', price: 200, duration: 120 },
      { name: 'Nature Photography', price: 175, duration: 120 },
      { name: 'Pet Photography', price: 150, duration: 60 },
      { name: 'Newborn Photography', price: 275, duration: 150 },
      { name: 'Maternity Photography', price: 225, duration: 90 },
      { name: 'Baby Photography', price: 175, duration: 60 },
      { name: 'Children Photography', price: 150, duration: 60 },
      { name: 'School Photography', price: 125, duration: 45 },
      { name: 'Sports Photography', price: 250, duration: 180 },
      { name: 'Action Photography', price: 275, duration: 180 },
      { name: 'Concert Photography', price: 350, duration: 240 },
      { name: 'Fashion Photography', price: 400, duration: 180 },
      { name: 'Model Portfolio', price: 350, duration: 180 },
      { name: 'Commercial Photography', price: 500, duration: 240 },
      { name: 'Advertising Photography', price: 600, duration: 300 },
      { name: 'Catalog Photography', price: 400, duration: 240 },
      { name: 'Lifestyle Photography', price: 300, duration: 150 },
      { name: 'Documentary Photography', price: 350, duration: 240 },
      { name: 'Photojournalism', price: 400, duration: 240 },
      { name: 'Photo Editing', price: 75, duration: 60 },
      { name: 'Photo Retouching', price: 50, duration: 30 },
      { name: 'Album Design', price: 200, duration: 180 },
      { name: 'Print Services', price: 50, duration: 0 },
      { name: 'Digital Delivery', price: 25, duration: 0 },
      { name: 'Photo Booth Rental', price: 400, duration: 180 },
      { name: '360 Photography', price: 300, duration: 150 },
      { name: 'Virtual Tour Creation', price: 500, duration: 240 },
      { name: 'Video Production', price: 600, duration: 300 },
      { name: 'Promotional Video', price: 500, duration: 240 },
      { name: 'Social Media Content', price: 250, duration: 120 },
      { name: 'Brand Photography', price: 400, duration: 180 },
      { name: 'Behind-the-Scenes', price: 250, duration: 180 },
      { name: 'Photography Workshop', price: 150, duration: 180 },
    ],
  },

  // 13. Fitness
  {
    id: 'fitness',
    name: 'Fitness',
    description: 'Group fitness classes, gym services, wellness',
    icon: 'Dumbbell',
    themeColor: '350 60% 50%',
    altColor: '350 40% 35%',
    businessType: 'stationary',
    services: [
      { name: 'Personal Training Session', price: 75, duration: 60 },
      { name: 'Group Fitness Class', price: 25, duration: 60 },
      { name: 'Strength Training', price: 70, duration: 60 },
      { name: 'Cardio Training', price: 50, duration: 45 },
      { name: 'HIIT Training', price: 65, duration: 45 },
      { name: 'Circuit Training', price: 60, duration: 45 },
      { name: 'CrossFit Training', price: 75, duration: 60 },
      { name: 'Weight Loss Program', price: 250, duration: 0 },
      { name: 'Muscle Building Program', price: 250, duration: 0 },
      { name: 'Endurance Training', price: 65, duration: 60 },
      { name: 'Flexibility Training', price: 50, duration: 45 },
      { name: 'Mobility Training', price: 55, duration: 45 },
      { name: 'Core Training', price: 55, duration: 45 },
      { name: 'Functional Training', price: 65, duration: 60 },
      { name: 'Sports-Specific Training', price: 80, duration: 60 },
      { name: 'Athletic Performance', price: 85, duration: 60 },
      { name: 'Speed Training', price: 70, duration: 45 },
      { name: 'Agility Training', price: 65, duration: 45 },
      { name: 'Balance Training', price: 50, duration: 45 },
      { name: 'Posture Correction', price: 60, duration: 45 },
      { name: 'Injury Rehabilitation', price: 75, duration: 60 },
      { name: 'Pre/Post Natal Fitness', price: 70, duration: 45 },
      { name: 'Senior Fitness', price: 55, duration: 45 },
      { name: 'Youth Fitness', price: 45, duration: 45 },
      { name: 'Beginner Program', price: 200, duration: 0 },
      { name: 'Advanced Training', price: 85, duration: 60 },
      { name: 'Competition Prep', price: 100, duration: 90 },
      { name: 'Body Composition Analysis', price: 50, duration: 30 },
      { name: 'Fitness Assessment', price: 75, duration: 60 },
      { name: 'Goal Setting Session', price: 50, duration: 45 },
      { name: 'Nutrition Coaching', price: 75, duration: 45 },
      { name: 'Meal Planning', price: 100, duration: 60 },
      { name: 'Supplement Guidance', price: 50, duration: 30 },
      { name: 'Yoga Class', price: 25, duration: 60 },
      { name: 'Pilates Class', price: 30, duration: 60 },
      { name: 'Barre Class', price: 25, duration: 55 },
      { name: 'Spin Class', price: 25, duration: 45 },
      { name: 'Kickboxing Class', price: 30, duration: 60 },
      { name: 'Boxing Training', price: 65, duration: 60 },
      { name: 'Martial Arts Training', price: 70, duration: 60 },
      { name: 'Swimming Lessons', price: 55, duration: 45 },
      { name: 'Running Coaching', price: 60, duration: 60 },
      { name: 'Marathon Training', price: 150, duration: 0 },
      { name: 'Triathlon Training', price: 200, duration: 0 },
      { name: 'Boot Camp', price: 25, duration: 45 },
      { name: 'Outdoor Training', price: 65, duration: 60 },
      { name: 'Virtual Training', price: 50, duration: 45 },
      { name: 'Online Coaching', price: 150, duration: 0 },
      { name: 'Wellness Coaching', price: 75, duration: 60 },
      { name: 'Lifestyle Coaching', price: 85, duration: 60 },
    ],
  },

  // 14. Catering
  {
    id: 'catering',
    name: 'Catering',
    description: 'Event catering, food service, meal preparation',
    icon: 'ChefHat',
    themeColor: '15 70% 45%',
    altColor: '15 50% 30%',
    businessType: 'mobile',
    services: [
      { name: 'Corporate Lunch Catering', price: 20, duration: 0 },
      { name: 'Corporate Dinner Catering', price: 35, duration: 0 },
      { name: 'Office Party Catering', price: 25, duration: 0 },
      { name: 'Business Meeting Catering', price: 18, duration: 0 },
      { name: 'Conference Catering', price: 22, duration: 0 },
      { name: 'Wedding Catering', price: 85, duration: 0 },
      { name: 'Rehearsal Dinner', price: 50, duration: 0 },
      { name: 'Engagement Party', price: 40, duration: 0 },
      { name: 'Birthday Party Catering', price: 30, duration: 0 },
      { name: 'Anniversary Party', price: 45, duration: 0 },
      { name: 'Graduation Party', price: 28, duration: 0 },
      { name: 'Holiday Party Catering', price: 40, duration: 0 },
      { name: 'Cocktail Party', price: 35, duration: 0 },
      { name: 'Hors d\'Oeuvres Service', price: 25, duration: 0 },
      { name: 'Buffet Service', price: 30, duration: 0 },
      { name: 'Plated Dinner Service', price: 55, duration: 0 },
      { name: 'Family Style Service', price: 40, duration: 0 },
      { name: 'Food Station Setup', price: 35, duration: 0 },
      { name: 'BBQ Catering', price: 28, duration: 0 },
      { name: 'Breakfast Catering', price: 15, duration: 0 },
      { name: 'Brunch Catering', price: 25, duration: 0 },
      { name: 'Lunch Box Delivery', price: 15, duration: 0 },
      { name: 'Drop-Off Catering', price: 20, duration: 0 },
      { name: 'Full-Service Catering', price: 50, duration: 0 },
      { name: 'Event Staffing', price: 30, duration: 60 },
      { name: 'Bartending Service', price: 35, duration: 60 },
      { name: 'Bar Setup', price: 200, duration: 0 },
      { name: 'Dessert Catering', price: 12, duration: 0 },
      { name: 'Cake Service', price: 8, duration: 0 },
      { name: 'Custom Menu Creation', price: 150, duration: 120 },
      { name: 'Dietary Accommodation', price: 5, duration: 0 },
      { name: 'Vegan Catering', price: 35, duration: 0 },
      { name: 'Vegetarian Catering', price: 30, duration: 0 },
      { name: 'Gluten-Free Options', price: 5, duration: 0 },
      { name: 'Kosher Catering', price: 45, duration: 0 },
      { name: 'Halal Catering', price: 40, duration: 0 },
      { name: 'Farm-to-Table', price: 55, duration: 0 },
      { name: 'Outdoor Event Catering', price: 35, duration: 0 },
      { name: 'Tent Event Catering', price: 40, duration: 0 },
      { name: 'Food Truck Service', price: 25, duration: 0 },
      { name: 'Private Chef Service', price: 150, duration: 180 },
      { name: 'In-Home Dinner Party', price: 75, duration: 0 },
      { name: 'Cooking Class', price: 100, duration: 180 },
      { name: 'Tasting Event', price: 50, duration: 120 },
      { name: 'Wine Pairing', price: 25, duration: 0 },
      { name: 'Equipment Rental', price: 100, duration: 0 },
      { name: 'Table Setting', price: 15, duration: 0 },
      { name: 'Cleanup Service', price: 150, duration: 120 },
      { name: 'Leftover Packaging', price: 25, duration: 0 },
      { name: 'Event Consultation', price: 75, duration: 60 },
    ],
  },

  // 15. Car Wash
  {
    id: 'car_wash',
    name: 'Car Wash',
    description: 'Auto washing, detailing, car care services',
    icon: 'Car',
    themeColor: '210 60% 50%',
    altColor: '210 40% 35%',
    businessType: 'stationary',
    services: [
      { name: 'Basic Exterior Wash', price: 15, duration: 15 },
      { name: 'Premium Exterior Wash', price: 25, duration: 25 },
      { name: 'Full Service Wash', price: 35, duration: 40 },
      { name: 'Hand Wash', price: 30, duration: 45 },
      { name: 'Touchless Wash', price: 20, duration: 20 },
      { name: 'Wheel Cleaning', price: 15, duration: 15 },
      { name: 'Tire Shine', price: 10, duration: 10 },
      { name: 'Rim Cleaning', price: 20, duration: 20 },
      { name: 'Undercarriage Wash', price: 15, duration: 15 },
      { name: 'Bug Removal', price: 15, duration: 15 },
      { name: 'Tar Removal', price: 20, duration: 20 },
      { name: 'Tree Sap Removal', price: 25, duration: 25 },
      { name: 'Bird Dropping Removal', price: 15, duration: 15 },
      { name: 'Water Spot Removal', price: 30, duration: 30 },
      { name: 'Clay Bar Treatment', price: 75, duration: 60 },
      { name: 'Wax Application', price: 50, duration: 45 },
      { name: 'Spray Wax', price: 20, duration: 15 },
      { name: 'Hand Wax', price: 75, duration: 60 },
      { name: 'Ceramic Coating', price: 300, duration: 240 },
      { name: 'Paint Sealant', price: 100, duration: 90 },
      { name: 'Paint Protection', price: 150, duration: 120 },
      { name: 'Scratch Removal', price: 75, duration: 60 },
      { name: 'Swirl Removal', price: 100, duration: 90 },
      { name: 'Paint Correction', price: 200, duration: 180 },
      { name: 'Headlight Restoration', price: 50, duration: 45 },
      { name: 'Chrome Polishing', price: 40, duration: 30 },
      { name: 'Trim Restoration', price: 35, duration: 30 },
      { name: 'Interior Vacuuming', price: 20, duration: 20 },
      { name: 'Interior Wipe Down', price: 25, duration: 25 },
      { name: 'Dashboard Cleaning', price: 15, duration: 15 },
      { name: 'Console Cleaning', price: 15, duration: 15 },
      { name: 'Door Panel Cleaning', price: 20, duration: 20 },
      { name: 'Carpet Shampooing', price: 50, duration: 45 },
      { name: 'Floor Mat Cleaning', price: 20, duration: 20 },
      { name: 'Seat Cleaning', price: 40, duration: 40 },
      { name: 'Leather Conditioning', price: 50, duration: 45 },
      { name: 'Fabric Protection', price: 40, duration: 30 },
      { name: 'Odor Elimination', price: 50, duration: 45 },
      { name: 'Air Freshener', price: 10, duration: 5 },
      { name: 'Window Cleaning - Interior', price: 15, duration: 15 },
      { name: 'Window Cleaning - Exterior', price: 15, duration: 15 },
      { name: 'Mirror Cleaning', price: 10, duration: 10 },
      { name: 'Trunk Cleaning', price: 25, duration: 25 },
      { name: 'Engine Bay Cleaning', price: 50, duration: 45 },
      { name: 'Detail Package - Basic', price: 100, duration: 90 },
      { name: 'Detail Package - Premium', price: 175, duration: 150 },
      { name: 'Detail Package - Complete', price: 275, duration: 240 },
      { name: 'Monthly Wash Plan', price: 45, duration: 0 },
      { name: 'Express Detail', price: 75, duration: 60 },
      { name: 'Full Detail', price: 250, duration: 210 },
    ],
  },

  // 16. Mobile Mechanic
  {
    id: 'mobile_mechanic',
    name: 'Mobile Mechanic',
    description: 'On-site auto repair and maintenance',
    icon: 'Wrench',
    themeColor: '0 60% 45%',
    altColor: '0 40% 30%',
    businessType: 'mobile',
    services: [
      { name: 'Oil Change', price: 75, duration: 45 },
      { name: 'Oil Filter Replacement', price: 25, duration: 15 },
      { name: 'Air Filter Replacement', price: 35, duration: 20 },
      { name: 'Cabin Air Filter', price: 45, duration: 25 },
      { name: 'Spark Plug Replacement', price: 125, duration: 60 },
      { name: 'Battery Replacement', price: 175, duration: 30 },
      { name: 'Battery Testing', price: 25, duration: 15 },
      { name: 'Jump Start Service', price: 50, duration: 30 },
      { name: 'Alternator Replacement', price: 400, duration: 120 },
      { name: 'Starter Replacement', price: 350, duration: 90 },
      { name: 'Brake Pad Replacement', price: 200, duration: 90 },
      { name: 'Brake Rotor Replacement', price: 350, duration: 120 },
      { name: 'Brake Fluid Flush', price: 95, duration: 45 },
      { name: 'Coolant Flush', price: 125, duration: 60 },
      { name: 'Transmission Fluid Change', price: 175, duration: 90 },
      { name: 'Power Steering Flush', price: 95, duration: 45 },
      { name: 'Fuel Filter Replacement', price: 95, duration: 45 },
      { name: 'Serpentine Belt Replace', price: 175, duration: 60 },
      { name: 'Timing Belt Replacement', price: 600, duration: 240 },
      { name: 'Water Pump Replacement', price: 450, duration: 180 },
      { name: 'Thermostat Replacement', price: 175, duration: 60 },
      { name: 'Radiator Repair', price: 350, duration: 120 },
      { name: 'Hose Replacement', price: 125, duration: 60 },
      { name: 'Fuel Pump Replacement', price: 500, duration: 180 },
      { name: 'Fuel Injector Cleaning', price: 125, duration: 60 },
      { name: 'Ignition Coil Replacement', price: 175, duration: 60 },
      { name: 'Oxygen Sensor Replace', price: 200, duration: 60 },
      { name: 'Mass Air Flow Sensor', price: 225, duration: 60 },
      { name: 'Throttle Body Cleaning', price: 95, duration: 45 },
      { name: 'PCV Valve Replacement', price: 75, duration: 30 },
      { name: 'EGR Valve Cleaning', price: 125, duration: 60 },
      { name: 'Catalytic Converter', price: 800, duration: 120 },
      { name: 'Exhaust Repair', price: 250, duration: 90 },
      { name: 'Muffler Replacement', price: 300, duration: 90 },
      { name: 'Shock Replacement', price: 350, duration: 120 },
      { name: 'Strut Replacement', price: 450, duration: 150 },
      { name: 'Tie Rod Replacement', price: 275, duration: 90 },
      { name: 'Ball Joint Replacement', price: 350, duration: 120 },
      { name: 'CV Axle Replacement', price: 375, duration: 120 },
      { name: 'Wheel Bearing Replace', price: 350, duration: 120 },
      { name: 'Hub Assembly', price: 400, duration: 120 },
      { name: 'Alignment Check', price: 75, duration: 30 },
      { name: 'Tire Rotation', price: 35, duration: 30 },
      { name: 'Tire Change', price: 25, duration: 20 },
      { name: 'Flat Tire Repair', price: 35, duration: 30 },
      { name: 'TPMS Service', price: 75, duration: 30 },
      { name: 'Diagnostic Scan', price: 75, duration: 30 },
      { name: 'Check Engine Light', price: 95, duration: 45 },
      { name: 'Pre-Purchase Inspection', price: 125, duration: 60 },
      { name: 'Roadside Assistance', price: 75, duration: 30 },
    ],
  },

  // 17. IT Support
  {
    id: 'it_support',
    name: 'IT Support',
    description: 'Computer repair, tech support, network services',
    icon: 'Monitor',
    themeColor: '220 60% 50%',
    altColor: '220 40% 35%',
    businessType: 'mobile',
    services: [
      { name: 'Computer Setup', price: 75, duration: 60 },
      { name: 'Computer Repair', price: 95, duration: 90 },
      { name: 'Laptop Repair', price: 125, duration: 120 },
      { name: 'Desktop Repair', price: 95, duration: 90 },
      { name: 'Virus Removal', price: 95, duration: 60 },
      { name: 'Malware Removal', price: 95, duration: 60 },
      { name: 'Spyware Removal', price: 85, duration: 60 },
      { name: 'Operating System Install', price: 95, duration: 90 },
      { name: 'Windows Installation', price: 95, duration: 90 },
      { name: 'Mac OS Installation', price: 95, duration: 90 },
      { name: 'Software Installation', price: 45, duration: 30 },
      { name: 'Software Update', price: 35, duration: 30 },
      { name: 'Driver Installation', price: 45, duration: 30 },
      { name: 'Data Backup', price: 75, duration: 60 },
      { name: 'Data Recovery', price: 150, duration: 120 },
      { name: 'Hard Drive Replacement', price: 150, duration: 90 },
      { name: 'SSD Upgrade', price: 175, duration: 90 },
      { name: 'RAM Upgrade', price: 95, duration: 45 },
      { name: 'Hardware Upgrade', price: 125, duration: 90 },
      { name: 'Screen Replacement', price: 200, duration: 120 },
      { name: 'Keyboard Replacement', price: 125, duration: 90 },
      { name: 'Battery Replacement', price: 95, duration: 60 },
      { name: 'Power Supply Replace', price: 125, duration: 60 },
      { name: 'Network Setup', price: 125, duration: 90 },
      { name: 'WiFi Setup', price: 75, duration: 45 },
      { name: 'Router Configuration', price: 65, duration: 45 },
      { name: 'Network Troubleshooting', price: 85, duration: 60 },
      { name: 'Internet Setup', price: 55, duration: 30 },
      { name: 'Email Setup', price: 45, duration: 30 },
      { name: 'Email Migration', price: 95, duration: 90 },
      { name: 'Cloud Setup', price: 85, duration: 60 },
      { name: 'Cloud Migration', price: 150, duration: 120 },
      { name: 'Printer Setup', price: 55, duration: 30 },
      { name: 'Printer Troubleshooting', price: 65, duration: 45 },
      { name: 'Scanner Setup', price: 45, duration: 30 },
      { name: 'Smart Home Setup', price: 125, duration: 90 },
      { name: 'Smart Device Config', price: 55, duration: 30 },
      { name: 'Password Recovery', price: 65, duration: 45 },
      { name: 'Account Recovery', price: 75, duration: 60 },
      { name: 'Security Assessment', price: 125, duration: 90 },
      { name: 'Firewall Setup', price: 95, duration: 60 },
      { name: 'VPN Setup', price: 75, duration: 45 },
      { name: 'Remote Access Setup', price: 85, duration: 60 },
      { name: 'System Optimization', price: 75, duration: 60 },
      { name: 'Startup Repair', price: 85, duration: 60 },
      { name: 'Blue Screen Fix', price: 95, duration: 90 },
      { name: 'Slow Computer Fix', price: 75, duration: 60 },
      { name: 'Training Session', price: 65, duration: 60 },
      { name: 'Tech Consultation', price: 50, duration: 30 },
      { name: 'Ongoing Support Plan', price: 150, duration: 0 },
    ],
  },

  // 18. Landscaping
  {
    id: 'landscaping',
    name: 'Landscaping',
    description: 'Garden design, hardscaping, outdoor projects',
    icon: 'Flower2',
    themeColor: '100 45% 40%',
    altColor: '100 35% 25%',
    businessType: 'mobile',
    services: [
      { name: 'Landscape Design', price: 500, duration: 300 },
      { name: 'Landscape Installation', price: 2500, duration: 1440 },
      { name: 'Garden Design', price: 350, duration: 180 },
      { name: 'Garden Installation', price: 1000, duration: 480 },
      { name: 'Tree Planting', price: 150, duration: 90 },
      { name: 'Shrub Planting', price: 75, duration: 45 },
      { name: 'Flower Planting', price: 50, duration: 30 },
      { name: 'Perennial Planting', price: 65, duration: 45 },
      { name: 'Annual Planting', price: 45, duration: 30 },
      { name: 'Bed Preparation', price: 200, duration: 180 },
      { name: 'Mulch Installation', price: 150, duration: 120 },
      { name: 'Rock Installation', price: 300, duration: 240 },
      { name: 'Gravel Installation', price: 250, duration: 180 },
      { name: 'Edging Installation', price: 125, duration: 90 },
      { name: 'Border Installation', price: 175, duration: 120 },
      { name: 'Retaining Wall', price: 1500, duration: 960 },
      { name: 'Stone Wall', price: 2000, duration: 1200 },
      { name: 'Paver Patio', price: 2500, duration: 1440 },
      { name: 'Paver Walkway', price: 1200, duration: 720 },
      { name: 'Flagstone Patio', price: 3000, duration: 1680 },
      { name: 'Flagstone Walkway', price: 1500, duration: 900 },
      { name: 'Concrete Patio', price: 2000, duration: 960 },
      { name: 'Stamped Concrete', price: 2500, duration: 1200 },
      { name: 'Deck Building', price: 5000, duration: 2880 },
      { name: 'Pergola Installation', price: 3500, duration: 1440 },
      { name: 'Arbor Installation', price: 1500, duration: 720 },
      { name: 'Fence Installation', price: 2500, duration: 1440 },
      { name: 'Gate Installation', price: 500, duration: 240 },
      { name: 'Water Feature', price: 2000, duration: 960 },
      { name: 'Fountain Installation', price: 1500, duration: 720 },
      { name: 'Pond Installation', price: 3000, duration: 1440 },
      { name: 'Waterfall Installation', price: 2500, duration: 1200 },
      { name: 'Irrigation Installation', price: 2000, duration: 960 },
      { name: 'Drip System', price: 500, duration: 300 },
      { name: 'Sprinkler Installation', price: 1500, duration: 720 },
      { name: 'Drainage Installation', price: 1200, duration: 720 },
      { name: 'French Drain', price: 1000, duration: 540 },
      { name: 'Dry Well', price: 800, duration: 480 },
      { name: 'Grading', price: 1500, duration: 720 },
      { name: 'Erosion Control', price: 1000, duration: 540 },
      { name: 'Sod Installation', price: 500, duration: 300 },
      { name: 'Artificial Turf', price: 2000, duration: 960 },
      { name: 'Outdoor Lighting', price: 1500, duration: 720 },
      { name: 'Path Lighting', price: 500, duration: 240 },
      { name: 'Accent Lighting', price: 750, duration: 360 },
      { name: 'Fire Pit Installation', price: 1500, duration: 720 },
      { name: 'Outdoor Kitchen', price: 10000, duration: 4320 },
      { name: 'Outdoor Fireplace', price: 5000, duration: 2400 },
      { name: 'Gazebo Installation', price: 4000, duration: 1920 },
      { name: 'Landscape Renovation', price: 3000, duration: 1440 },
    ],
  },

  // 19. Moving
  {
    id: 'moving',
    name: 'Moving',
    description: 'Residential and commercial moving services',
    icon: 'Package',
    themeColor: '30 50% 45%',
    altColor: '30 35% 30%',
    businessType: 'mobile',
    services: [
      { name: 'Local Moving', price: 100, duration: 60 },
      { name: 'Long Distance Moving', price: 250, duration: 0 },
      { name: 'Interstate Moving', price: 500, duration: 0 },
      { name: 'Residential Moving', price: 125, duration: 60 },
      { name: 'Apartment Moving', price: 100, duration: 60 },
      { name: 'House Moving', price: 175, duration: 60 },
      { name: 'Condo Moving', price: 125, duration: 60 },
      { name: 'Office Moving', price: 200, duration: 60 },
      { name: 'Commercial Moving', price: 250, duration: 60 },
      { name: 'Corporate Relocation', price: 300, duration: 60 },
      { name: 'Senior Moving', price: 150, duration: 60 },
      { name: 'Student Moving', price: 85, duration: 60 },
      { name: 'Military Moving', price: 125, duration: 60 },
      { name: 'Packing Services', price: 50, duration: 60 },
      { name: 'Unpacking Services', price: 50, duration: 60 },
      { name: 'Packing Supplies', price: 35, duration: 0 },
      { name: 'Box Delivery', price: 25, duration: 0 },
      { name: 'Furniture Disassembly', price: 50, duration: 45 },
      { name: 'Furniture Assembly', price: 75, duration: 60 },
      { name: 'Furniture Moving', price: 100, duration: 60 },
      { name: 'Heavy Item Moving', price: 150, duration: 60 },
      { name: 'Piano Moving', price: 350, duration: 120 },
      { name: 'Gun Safe Moving', price: 300, duration: 90 },
      { name: 'Hot Tub Moving', price: 500, duration: 180 },
      { name: 'Pool Table Moving', price: 400, duration: 150 },
      { name: 'Appliance Moving', price: 100, duration: 45 },
      { name: 'Electronics Moving', price: 75, duration: 30 },
      { name: 'Art Moving', price: 150, duration: 60 },
      { name: 'Antique Moving', price: 200, duration: 90 },
      { name: 'Fragile Item Packing', price: 75, duration: 45 },
      { name: 'Specialty Crating', price: 150, duration: 90 },
      { name: 'Vehicle Transport', price: 500, duration: 0 },
      { name: 'Storage Services', price: 150, duration: 0 },
      { name: 'Short-Term Storage', price: 100, duration: 0 },
      { name: 'Long-Term Storage', price: 200, duration: 0 },
      { name: 'Climate-Controlled Storage', price: 250, duration: 0 },
      { name: 'Loading Only', price: 75, duration: 60 },
      { name: 'Unloading Only', price: 75, duration: 60 },
      { name: 'Labor Only', price: 50, duration: 60 },
      { name: 'Truck Rental Assistance', price: 50, duration: 30 },
      { name: 'Moving Consultation', price: 0, duration: 30 },
      { name: 'Pre-Move Survey', price: 0, duration: 45 },
      { name: 'Inventory Service', price: 75, duration: 60 },
      { name: 'Junk Removal', price: 150, duration: 90 },
      { name: 'Donation Pickup', price: 75, duration: 45 },
      { name: 'Cleaning After Move', price: 150, duration: 120 },
      { name: 'Estate Moving', price: 200, duration: 60 },
      { name: 'Emergency Moving', price: 175, duration: 60 },
      { name: 'Same-Day Moving', price: 200, duration: 60 },
      { name: 'White Glove Service', price: 250, duration: 60 },
    ],
  },

  // 20. Auto Repair
  {
    id: 'auto_repair',
    name: 'Auto Repair',
    description: 'Full-service automotive repair shop',
    icon: 'Car',
    themeColor: '220 45% 35%',
    altColor: '220 30% 25%',
    businessType: 'stationary',
    services: [
      { name: 'Engine Diagnostics', price: 95, duration: 60 },
      { name: 'Engine Repair', price: 500, duration: 300 },
      { name: 'Engine Rebuild', price: 3000, duration: 1920 },
      { name: 'Engine Replacement', price: 4000, duration: 2400 },
      { name: 'Transmission Repair', price: 800, duration: 480 },
      { name: 'Transmission Rebuild', price: 2500, duration: 1440 },
      { name: 'Transmission Replacement', price: 3500, duration: 960 },
      { name: 'Clutch Replacement', price: 800, duration: 360 },
      { name: 'Differential Repair', price: 600, duration: 300 },
      { name: 'Axle Repair', price: 400, duration: 180 },
      { name: 'Suspension Repair', price: 500, duration: 240 },
      { name: 'Steering Repair', price: 400, duration: 180 },
      { name: 'Brake System Repair', price: 350, duration: 180 },
      { name: 'ABS Repair', price: 400, duration: 180 },
      { name: 'Electrical System Repair', price: 300, duration: 180 },
      { name: 'Wiring Repair', price: 200, duration: 120 },
      { name: 'Fuse Replacement', price: 50, duration: 30 },
      { name: 'Sensor Replacement', price: 200, duration: 90 },
      { name: 'Computer Diagnostics', price: 125, duration: 60 },
      { name: 'ECU Programming', price: 250, duration: 120 },
      { name: 'Emission Testing', price: 50, duration: 30 },
      { name: 'Emission Repair', price: 400, duration: 180 },
      { name: 'Exhaust System Repair', price: 350, duration: 180 },
      { name: 'Catalytic Converter Replace', price: 1000, duration: 180 },
      { name: 'Muffler Replacement', price: 300, duration: 120 },
      { name: 'Fuel System Repair', price: 400, duration: 180 },
      { name: 'Fuel Injection Service', price: 150, duration: 90 },
      { name: 'Carburetor Repair', price: 300, duration: 180 },
      { name: 'Cooling System Repair', price: 350, duration: 180 },
      { name: 'Radiator Replacement', price: 450, duration: 180 },
      { name: 'Heater Core Replacement', price: 600, duration: 360 },
      { name: 'AC Repair', price: 300, duration: 120 },
      { name: 'AC Recharge', price: 150, duration: 60 },
      { name: 'Compressor Replacement', price: 600, duration: 180 },
      { name: 'Timing Chain Replacement', price: 800, duration: 360 },
      { name: 'Head Gasket Repair', price: 1200, duration: 720 },
      { name: 'Valve Adjustment', price: 300, duration: 180 },
      { name: 'Oil Leak Repair', price: 350, duration: 180 },
      { name: 'Gasket Replacement', price: 250, duration: 150 },
      { name: 'Seal Replacement', price: 200, duration: 120 },
      { name: 'Drivability Diagnosis', price: 125, duration: 90 },
      { name: 'Performance Tuning', price: 350, duration: 180 },
      { name: 'Engine Tune-Up', price: 200, duration: 120 },
      { name: 'Fleet Service', price: 150, duration: 90 },
      { name: 'Warranty Service', price: 0, duration: 120 },
      { name: 'Factory Maintenance', price: 175, duration: 120 },
      { name: 'Recall Service', price: 0, duration: 120 },
      { name: 'State Inspection', price: 35, duration: 30 },
      { name: 'Safety Inspection', price: 50, duration: 45 },
      { name: 'Pre-Purchase Inspection', price: 125, duration: 90 },
    ],
  },

  // 21. Hair Stylist
  {
    id: 'hair_stylist',
    name: 'Hair Stylist',
    description: 'Professional hair styling and coloring',
    icon: 'Scissors',
    themeColor: '300 40% 45%',
    altColor: '300 30% 30%',
    businessType: 'stationary',
    services: [
      { name: 'Women\'s Haircut', price: 55, duration: 60 },
      { name: 'Men\'s Haircut', price: 35, duration: 30 },
      { name: 'Children\'s Haircut', price: 25, duration: 25 },
      { name: 'Long Hair Trim', price: 45, duration: 45 },
      { name: 'Short Hair Cut', price: 40, duration: 35 },
      { name: 'Layered Cut', price: 55, duration: 50 },
      { name: 'Bob Haircut', price: 50, duration: 45 },
      { name: 'Pixie Cut', price: 45, duration: 40 },
      { name: 'Undercut', price: 40, duration: 35 },
      { name: 'Asymmetrical Cut', price: 55, duration: 50 },
      { name: 'Bang Cut', price: 15, duration: 15 },
      { name: 'Face Framing', price: 25, duration: 20 },
      { name: 'Texturizing', price: 20, duration: 15 },
      { name: 'Thinning', price: 15, duration: 15 },
      { name: 'Hair Coloring', price: 95, duration: 120 },
      { name: 'Single Process Color', price: 85, duration: 90 },
      { name: 'Double Process Color', price: 150, duration: 180 },
      { name: 'Partial Highlights', price: 100, duration: 90 },
      { name: 'Full Highlights', price: 150, duration: 150 },
      { name: 'Lowlights', price: 95, duration: 90 },
      { name: 'Balayage', price: 200, duration: 180 },
      { name: 'Ombre', price: 175, duration: 150 },
      { name: 'Sombre', price: 165, duration: 135 },
      { name: 'Color Correction', price: 250, duration: 240 },
      { name: 'Toner Application', price: 40, duration: 30 },
      { name: 'Gloss Treatment', price: 45, duration: 30 },
      { name: 'Root Touch-Up', price: 65, duration: 60 },
      { name: 'Gray Blending', price: 75, duration: 60 },
      { name: 'Fashion Colors', price: 150, duration: 150 },
      { name: 'Vivid Colors', price: 200, duration: 180 },
      { name: 'Dimensional Color', price: 175, duration: 150 },
      { name: 'Blowout', price: 45, duration: 45 },
      { name: 'Wash and Style', price: 35, duration: 30 },
      { name: 'Formal Styling', price: 85, duration: 60 },
      { name: 'Bridal Hair', price: 175, duration: 120 },
      { name: 'Wedding Party Hair', price: 95, duration: 60 },
      { name: 'Prom Hair', price: 85, duration: 60 },
      { name: 'Updo', price: 75, duration: 60 },
      { name: 'Half-Up Style', price: 55, duration: 45 },
      { name: 'Braiding', price: 65, duration: 60 },
      { name: 'Extensions Consultation', price: 0, duration: 30 },
      { name: 'Tape-In Extensions', price: 400, duration: 180 },
      { name: 'Sew-In Extensions', price: 450, duration: 240 },
      { name: 'Keratin Treatment', price: 275, duration: 180 },
      { name: 'Smoothing Treatment', price: 225, duration: 150 },
      { name: 'Deep Conditioning', price: 45, duration: 30 },
      { name: 'Scalp Treatment', price: 50, duration: 30 },
      { name: 'Hair Mask', price: 40, duration: 30 },
      { name: 'Olaplex Treatment', price: 55, duration: 30 },
      { name: 'Consultation', price: 0, duration: 15 },
    ],
  },

  // 22. Massage
  {
    id: 'massage',
    name: 'Massage',
    description: 'Therapeutic massage and bodywork',
    icon: 'Heart',
    themeColor: '280 35% 50%',
    altColor: '280 25% 35%',
    businessType: 'stationary',
    services: [
      { name: 'Swedish Massage', price: 80, duration: 60 },
      { name: 'Deep Tissue Massage', price: 100, duration: 60 },
      { name: 'Sports Massage', price: 95, duration: 60 },
      { name: 'Therapeutic Massage', price: 90, duration: 60 },
      { name: 'Relaxation Massage', price: 75, duration: 60 },
      { name: 'Hot Stone Massage', price: 120, duration: 75 },
      { name: 'Cold Stone Massage', price: 115, duration: 75 },
      { name: 'Aromatherapy Massage', price: 95, duration: 60 },
      { name: 'Prenatal Massage', price: 85, duration: 60 },
      { name: 'Postnatal Massage', price: 85, duration: 60 },
      { name: 'Couples Massage', price: 180, duration: 60 },
      { name: 'Four Hands Massage', price: 200, duration: 60 },
      { name: 'Thai Massage', price: 100, duration: 90 },
      { name: 'Shiatsu Massage', price: 95, duration: 60 },
      { name: 'Reflexology', price: 65, duration: 45 },
      { name: 'Foot Massage', price: 50, duration: 30 },
      { name: 'Hand Massage', price: 35, duration: 20 },
      { name: 'Scalp Massage', price: 40, duration: 30 },
      { name: 'Face Massage', price: 45, duration: 30 },
      { name: 'Neck & Shoulder Massage', price: 50, duration: 30 },
      { name: 'Back Massage', price: 60, duration: 30 },
      { name: 'Full Body Massage', price: 100, duration: 90 },
      { name: 'Chair Massage', price: 35, duration: 20 },
      { name: 'Corporate Massage', price: 45, duration: 20 },
      { name: 'Event Massage', price: 45, duration: 20 },
      { name: 'Trigger Point Therapy', price: 100, duration: 60 },
      { name: 'Myofascial Release', price: 110, duration: 60 },
      { name: 'Neuromuscular Therapy', price: 110, duration: 60 },
      { name: 'Lymphatic Drainage', price: 100, duration: 60 },
      { name: 'Craniosacral Therapy', price: 95, duration: 60 },
      { name: 'Cupping Therapy', price: 75, duration: 45 },
      { name: 'Gua Sha', price: 65, duration: 30 },
      { name: 'Stretching Session', price: 60, duration: 45 },
      { name: 'Assisted Stretching', price: 70, duration: 45 },
      { name: 'PNF Stretching', price: 75, duration: 45 },
      { name: 'Muscle Energy Technique', price: 85, duration: 45 },
      { name: 'Joint Mobilization', price: 80, duration: 45 },
      { name: 'Injury Rehabilitation', price: 100, duration: 60 },
      { name: 'Pain Management', price: 95, duration: 60 },
      { name: 'Stress Relief', price: 80, duration: 60 },
      { name: 'Insomnia Treatment', price: 85, duration: 60 },
      { name: 'Headache Relief', price: 70, duration: 45 },
      { name: 'TMJ Massage', price: 75, duration: 45 },
      { name: 'Carpal Tunnel Massage', price: 65, duration: 30 },
      { name: 'Sciatica Relief', price: 90, duration: 60 },
      { name: 'Fibromyalgia Massage', price: 95, duration: 60 },
      { name: 'Senior Massage', price: 75, duration: 60 },
      { name: 'Pediatric Massage', price: 55, duration: 30 },
      { name: 'Mobile Massage', price: 125, duration: 60 },
      { name: 'Subscription Package', price: 250, duration: 0 },
    ],
  },

  // 23. Bakery
  {
    id: 'bakery',
    name: 'Bakery',
    description: 'Custom cakes, pastries, baked goods',
    icon: 'Cake',
    themeColor: '35 65% 55%',
    altColor: '35 50% 40%',
    businessType: 'stationary',
    services: [
      { name: 'Custom Birthday Cake', price: 75, duration: 0 },
      { name: 'Wedding Cake', price: 500, duration: 0 },
      { name: 'Tiered Cake', price: 150, duration: 0 },
      { name: 'Sheet Cake', price: 45, duration: 0 },
      { name: 'Cupcakes - Dozen', price: 36, duration: 0 },
      { name: 'Custom Cupcakes', price: 48, duration: 0 },
      { name: 'Mini Cupcakes', price: 24, duration: 0 },
      { name: 'Cake Pops', price: 30, duration: 0 },
      { name: 'Cookies - Dozen', price: 24, duration: 0 },
      { name: 'Custom Cookies', price: 36, duration: 0 },
      { name: 'Decorated Cookies', price: 48, duration: 0 },
      { name: 'Cookie Platters', price: 45, duration: 0 },
      { name: 'Brownies', price: 24, duration: 0 },
      { name: 'Blondies', price: 24, duration: 0 },
      { name: 'Bars and Squares', price: 28, duration: 0 },
      { name: 'Muffins', price: 18, duration: 0 },
      { name: 'Scones', price: 21, duration: 0 },
      { name: 'Croissants', price: 27, duration: 0 },
      { name: 'Danish Pastries', price: 24, duration: 0 },
      { name: 'Cinnamon Rolls', price: 30, duration: 0 },
      { name: 'Donuts', price: 18, duration: 0 },
      { name: 'Fruit Tarts', price: 35, duration: 0 },
      { name: 'Cream Puffs', price: 28, duration: 0 },
      { name: 'Eclairs', price: 32, duration: 0 },
      { name: 'Macarons', price: 36, duration: 0 },
      { name: 'Cheesecake', price: 55, duration: 0 },
      { name: 'Fruit Pie', price: 35, duration: 0 },
      { name: 'Cream Pie', price: 40, duration: 0 },
      { name: 'Savory Pie', price: 38, duration: 0 },
      { name: 'Bread Loaves', price: 8, duration: 0 },
      { name: 'Artisan Bread', price: 12, duration: 0 },
      { name: 'Baguettes', price: 6, duration: 0 },
      { name: 'Rolls and Buns', price: 8, duration: 0 },
      { name: 'Focaccia', price: 10, duration: 0 },
      { name: 'Brioche', price: 9, duration: 0 },
      { name: 'Pretzel Products', price: 12, duration: 0 },
      { name: 'Bagels', price: 15, duration: 0 },
      { name: 'English Muffins', price: 12, duration: 0 },
      { name: 'Gluten-Free Options', price: 0, duration: 0 },
      { name: 'Vegan Options', price: 0, duration: 0 },
      { name: 'Sugar-Free Options', price: 0, duration: 0 },
      { name: 'Keto Options', price: 0, duration: 0 },
      { name: 'Breakfast Pastries', price: 25, duration: 0 },
      { name: 'Dessert Platters', price: 65, duration: 0 },
      { name: 'Catering Packages', price: 150, duration: 0 },
      { name: 'Wedding Dessert Bar', price: 300, duration: 0 },
      { name: 'Corporate Orders', price: 100, duration: 0 },
      { name: 'Holiday Specials', price: 0, duration: 0 },
      { name: 'Cake Decorating Class', price: 75, duration: 120 },
      { name: 'Custom Consultation', price: 0, duration: 30 },
    ],
  },

  // 24. Personal Training
  {
    id: 'personal_training',
    name: 'Personal Training',
    description: 'One-on-one fitness coaching and programs',
    icon: 'Dumbbell',
    themeColor: '10 70% 50%',
    altColor: '10 50% 35%',
    businessType: 'mobile',
    services: [
      { name: 'Initial Fitness Assessment', price: 95, duration: 90 },
      { name: 'Goal Setting Session', price: 50, duration: 45 },
      { name: 'Program Design', price: 150, duration: 120 },
      { name: 'One-on-One Training', price: 75, duration: 60 },
      { name: 'Partner Training', price: 100, duration: 60 },
      { name: 'Small Group Training', price: 40, duration: 60 },
      { name: 'Weight Loss Training', price: 80, duration: 60 },
      { name: 'Muscle Building', price: 80, duration: 60 },
      { name: 'Body Toning', price: 75, duration: 60 },
      { name: 'Strength Training', price: 75, duration: 60 },
      { name: 'Powerlifting Training', price: 85, duration: 75 },
      { name: 'Olympic Lifting', price: 90, duration: 75 },
      { name: 'Kettlebell Training', price: 70, duration: 45 },
      { name: 'TRX Training', price: 70, duration: 45 },
      { name: 'Resistance Band Training', price: 65, duration: 45 },
      { name: 'Bodyweight Training', price: 65, duration: 45 },
      { name: 'Core Strengthening', price: 60, duration: 45 },
      { name: 'Functional Fitness', price: 75, duration: 60 },
      { name: 'Sports Performance', price: 90, duration: 60 },
      { name: 'Speed and Agility', price: 80, duration: 60 },
      { name: 'Flexibility Training', price: 55, duration: 45 },
      { name: 'Mobility Work', price: 55, duration: 45 },
      { name: 'Injury Prevention', price: 70, duration: 45 },
      { name: 'Post-Rehab Training', price: 85, duration: 60 },
      { name: 'Pre/Post Natal Training', price: 75, duration: 45 },
      { name: 'Senior Fitness', price: 65, duration: 45 },
      { name: 'Youth Athletics', price: 60, duration: 45 },
      { name: 'Beginner Program', price: 65, duration: 60 },
      { name: 'Advanced Training', price: 85, duration: 60 },
      { name: 'Competition Prep', price: 100, duration: 90 },
      { name: 'Physique Coaching', price: 95, duration: 75 },
      { name: 'Nutrition Planning', price: 125, duration: 60 },
      { name: 'Macro Coaching', price: 75, duration: 45 },
      { name: 'Supplement Guidance', price: 50, duration: 30 },
      { name: 'Lifestyle Coaching', price: 85, duration: 60 },
      { name: 'Accountability Coaching', price: 150, duration: 0 },
      { name: 'Progress Tracking', price: 50, duration: 30 },
      { name: 'Body Composition Test', price: 75, duration: 30 },
      { name: 'VO2 Max Testing', price: 150, duration: 60 },
      { name: 'Metabolic Testing', price: 125, duration: 45 },
      { name: 'Movement Screening', price: 75, duration: 45 },
      { name: 'Corrective Exercise', price: 70, duration: 45 },
      { name: 'Postural Analysis', price: 65, duration: 30 },
      { name: 'Foam Rolling Session', price: 45, duration: 30 },
      { name: 'Recovery Session', price: 55, duration: 45 },
      { name: 'Virtual Training', price: 55, duration: 45 },
      { name: 'Online Programming', price: 200, duration: 0 },
      { name: 'Monthly Check-In', price: 100, duration: 0 },
      { name: 'Weekly Check-In', price: 50, duration: 0 },
      { name: 'Transformation Program', price: 500, duration: 0 },
    ],
  },

  // 25. Event Planning
  {
    id: 'event_planning',
    name: 'Event Planning',
    description: 'Wedding and corporate event coordination',
    icon: 'PartyPopper',
    themeColor: '320 50% 50%',
    altColor: '320 35% 35%',
    businessType: 'stationary',
    services: [
      { name: 'Full Wedding Planning', price: 5000, duration: 0 },
      { name: 'Partial Wedding Planning', price: 2500, duration: 0 },
      { name: 'Wedding Day Coordination', price: 1500, duration: 720 },
      { name: 'Corporate Event Planning', price: 2000, duration: 0 },
      { name: 'Conference Planning', price: 3000, duration: 0 },
      { name: 'Seminar Coordination', price: 1500, duration: 0 },
      { name: 'Trade Show Management', price: 2500, duration: 0 },
      { name: 'Product Launch', price: 3000, duration: 0 },
      { name: 'Grand Opening', price: 1500, duration: 0 },
      { name: 'Gala Planning', price: 4000, duration: 0 },
      { name: 'Fundraiser Planning', price: 2500, duration: 0 },
      { name: 'Charity Event', price: 2000, duration: 0 },
      { name: 'Anniversary Party', price: 1000, duration: 0 },
      { name: 'Birthday Party - Adult', price: 750, duration: 0 },
      { name: 'Birthday Party - Children', price: 500, duration: 0 },
      { name: 'Graduation Party', price: 600, duration: 0 },
      { name: 'Retirement Party', price: 800, duration: 0 },
      { name: 'Baby Shower', price: 500, duration: 0 },
      { name: 'Bridal Shower', price: 600, duration: 0 },
      { name: 'Engagement Party', price: 750, duration: 0 },
      { name: 'Rehearsal Dinner', price: 800, duration: 0 },
      { name: 'Holiday Party', price: 1000, duration: 0 },
      { name: 'New Year\'s Event', price: 1500, duration: 0 },
      { name: 'Summer Party', price: 800, duration: 0 },
      { name: 'Theme Party', price: 1000, duration: 0 },
      { name: 'Destination Event', price: 5000, duration: 0 },
      { name: 'Outdoor Event', price: 1200, duration: 0 },
      { name: 'Tent Event', price: 1500, duration: 0 },
      { name: 'Venue Selection', price: 500, duration: 300 },
      { name: 'Vendor Coordination', price: 750, duration: 0 },
      { name: 'Catering Coordination', price: 400, duration: 0 },
      { name: 'Entertainment Booking', price: 300, duration: 120 },
      { name: 'DJ Booking', price: 200, duration: 60 },
      { name: 'Band Booking', price: 350, duration: 120 },
      { name: 'Photography Coordination', price: 250, duration: 60 },
      { name: 'Videography Coordination', price: 250, duration: 60 },
      { name: 'Floral Design', price: 500, duration: 0 },
      { name: 'Decor Setup', price: 750, duration: 240 },
      { name: 'Table Setting', price: 300, duration: 120 },
      { name: 'Invitation Design', price: 350, duration: 180 },
      { name: 'RSVP Management', price: 200, duration: 0 },
      { name: 'Guest List Management', price: 150, duration: 0 },
      { name: 'Seating Chart', price: 200, duration: 120 },
      { name: 'Timeline Creation', price: 250, duration: 120 },
      { name: 'Day-Of Coordination', price: 1000, duration: 600 },
      { name: 'Event Staffing', price: 500, duration: 0 },
      { name: 'Rental Coordination', price: 300, duration: 0 },
      { name: 'Transportation Coord', price: 250, duration: 0 },
      { name: 'Budget Management', price: 400, duration: 0 },
      { name: 'Post-Event Cleanup', price: 500, duration: 240 },
    ],
  },
];

// Helper function to get a category by ID
export function getServiceCategoryById(id: string): ServiceCategory | undefined {
  return SERVICE_LIBRARY.find(cat => cat.id === id);
}

// Helper function to get all mobile categories
export function getMobileCategories(): ServiceCategory[] {
  return SERVICE_LIBRARY.filter(cat => cat.businessType === 'mobile');
}

// Helper function to get all stationary categories
export function getStationaryCategories(): ServiceCategory[] {
  return SERVICE_LIBRARY.filter(cat => cat.businessType === 'stationary');
}

// Export category IDs for type safety
export type ServiceCategoryId = typeof SERVICE_LIBRARY[number]['id'];
